# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'HumOS' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "PubNub"

  # Pods for HumOS

  target 'HumOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
