# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d120353b4bcc9e9b0e95b7135e70721bf3527a188061f7db811b2f069ee88f46bfe4ed1b11f961e7c5633589707051baf381e6138264483075c3fda7ccf7c20f

test:
  secret_key_base: 7e82e80bb33b322bc68b13441c0307dbbea4c864c29078928c375d2c50374cff8294ffb684b20c8cb290817d2b7f2ae28ac134677272eb766650f60078f60fba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
